run:
  timeout: 10m
  skip-files:
    - ".*\\.pb\\.go$"
  modules-download-mode: vendor

linters:
  enable:
    - gofmt
    - govet
    - depguard
    - goimports
    - ineffassign
    - misspell
    - unused
    - revive
    - staticcheck
    - typecheck
    - nolintlint
  disable-all: true

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
    packages:
      # The io/ioutil package has been deprecated.
      # https://go.dev/doc/go1.16#ioutil
      - io/ioutil

issues:
  exclude-rules:
    - linters:
        - revive
      text: "stutters"
