name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REPO_SLUG: tonistiigi/binfmt

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - ./hack/lint
          - ./hack/validate-vendor
          - ./hack/install-and-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run
        run: |
          ${{ matrix.script }}

  build:
    runs-on: ubuntu-latest
    needs: [ validate ]
    strategy:
      fail-fast: false
      matrix:
        target:
          - mainline
          - buildkit
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.binfmt-cache
          key: ${{ runner.os }}-binfmt-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-binfmt-${{ matrix.target }}-
            ${{ runner.os }}-binfmt-
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPO_SLUG }}
          tags: |
            type=ref,event=branch,enable=${{ matrix.target == 'mainline' }}
            type=ref,event=branch,prefix=${{ matrix.target }}-,enable=${{ matrix.target != 'mainline' }}
          flavor: |
            latest=false
          labels: |
            org.opencontainers.image.title=Binfmt
            org.opencontainers.image.description=Cross-platform emulator collection distributed with Docker images
          bake-target: meta-helper
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          config: .github/buildkit.toml
      -
        name: Test
        if: matrix.target == 'buildkit'
        uses: docker/bake-action@v1
        with:
          targets: buildkit-test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      -
        name: Build ${{ matrix.target }}
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: ${{ matrix.target }}-all
          push: ${{ startsWith(github.ref, 'refs/heads/') }}
          set: |
            *.cache-from=type=local,src=/tmp/.binfmt-cache/${{ matrix.target }}
            *.cache-to=type=local,dest=/tmp/.binfmt-cache/${{ matrix.target }}-new
      -
        # FIXME: Temp fix for https://github.com/moby/buildkit/issues/1850
        name: Move cache
        run: |
          rm -rf /tmp/.binfmt-cache/${{ matrix.target }}
          mv /tmp/.binfmt-cache/${{ matrix.target }}-new /tmp/.binfmt-cache/${{ matrix.target }}
