name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script:
          - ./hack/lint
          - ./hack/validate-vendor
          - ./hack/install-and-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Run
        run: |
          ${{ matrix.script }}

  build-base:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.prep.outputs.tag }}
      push: ${{ steps.prep.outputs.push }}
    steps:
      -
        name: Prepare
        id: prep
        run: |
          TAG=na
          PUSH=false
          if [[ $GITHUB_REF == refs/pull/* ]]; then
            TAG=pr-${{ github.event.number }}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            TAG=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            PUSH=true
          fi
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=push::${PUSH}

  build:
    runs-on: ubuntu-latest
    needs: [ validate, build-base ]
    strategy:
      fail-fast: false
      matrix:
        target:
          - mainline-all
          - buildkit-all
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.binfmt-cache
          key: ${{ runner.os }}-binfmt-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-binfmt-${{ matrix.target }}-
            ${{ runner.os }}-binfmt-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Test
        if: matrix.target == 'buildkit-all'
        uses: docker/bake-action@v1
        with:
          targets: buildkit-test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Login to DockerHub
        if: needs.build-base.outputs.push == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      -
        name: Build ${{ matrix.target }}
        uses: docker/bake-action@v1
        with:
          targets: ${{ matrix.target }}
          push: ${{ needs.build-base.outputs.push }}
          set: |
            *.cache-from=type=local,src=/tmp/.binfmt-cache/${{ matrix.target }}
            *.cache-to=type=local,dest=/tmp/.binfmt-cache/${{ matrix.target }}-new
        env:
          TAG: ${{ needs.build-base.outputs.tag }}
      -
        # FIXME: Temp fix for https://github.com/moby/buildkit/issues/1850
        name: Move cache
        run: |
          rm -rf /tmp/.binfmt-cache/${{ matrix.target }}
          mv /tmp/.binfmt-cache/${{ matrix.target }}-new /tmp/.binfmt-cache/${{ matrix.target }}
