name: deploy

on: [deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      - name: Setup builder
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment info
        id: info
        run: |
          echo "::set-output name=deployment_id::$(cat $GITHUB_EVENT_PATH | jq .deployment.id)"
          echo "::set-output name=deployment_target::$(cat $GITHUB_EVENT_PATH | jq -r .deployment.payload.target)"
      - name: Build and push
        env:
          DEPLOYMENT_TARGET: "${{ steps.info.outputs.deployment_target }}"
        if: ${{ success() }}
        id: build
        run: |
          docker run --rm --privileged tonistiigi/binfmt --install=all
          [ -n "$DEPLOYMENT_TARGET" ] || exit 1
          docker buildx bake --push --progress=plain $DEPLOYMENT_TARGET
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          target_url: "https://github.com/${{github.repository}}/actions/runs/${{ env.GITHUB_RUN_ID }}"
          state: "success"
          deployment_id: ${{ steps.info.outputs.deployment_id }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          target_url: "https://github.com/${{github.repository}}/actions/runs/${{ env.GITHUB_RUN_ID }}"
          state: "failure"
          deployment_id: ${{ steps.info.outputs.deployment_id }}
          token: ${{ secrets.GITHUB_TOKEN }}