name: e2e

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  dockerfile:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - tonistiigi/binfmt:latest
          - tonistiigi/binfmt:master
        dockerfile:
          - pip-youtube-dl
          - webpack
        platform:
          - linux/arm/v7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: ${{ matrix.image }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Test
        working-directory: test/dockerfiles/${{ matrix.dockerfile }}
        run: |
          docker buildx build --platform ${{ matrix.platform }} --output type=cacheonly .
